package cl.mp.rgp;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GestionRest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String idTarea;
	private java.lang.String idCausa;
	private java.lang.String fiscalia;

	public GestionRest() {
	}

	public java.lang.String getIdTarea() {
		return this.idTarea;
	}

	public void setIdTarea(java.lang.String idTarea) {
		this.idTarea = idTarea;
	}

	public java.lang.String getIdCausa() {
		return this.idCausa;
	}

	public void setIdCausa(java.lang.String idCausa) {
		this.idCausa = idCausa;
	}

	public java.lang.String getFiscalia() {
		return this.fiscalia;
	}

	public void setFiscalia(java.lang.String fiscalia) {
		this.fiscalia = fiscalia;
	}

	public GestionRest(java.lang.String idTarea, java.lang.String idCausa,
			java.lang.String fiscalia) {
		this.idTarea = idTarea;
		this.idCausa = idCausa;
		this.fiscalia = fiscalia;
	}

}