package cl.mp.rgp;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class respDM implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String response;

	public respDM() {
	}

	public java.lang.String getResponse() {
		return this.response;
	}

	public void setResponse(java.lang.String response) {
		this.response = response;
	}

	public respDM(java.lang.String response) {
		this.response = response;
	}

}